version: "3.9"
services:
  flask:
    image: aboutjoo/docker-memo:latest
    ports:
      - "80:8080"
  mongo:
    image: mongo:latest
    volumes:
      - mongo:/data/db/
    ports:
      - "27017:27017"

volumes:
  mongo: